# Generated by Django 4.0.5 on 2023-04-15 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='create_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
    ]
