# Generated by Django 4.0.5 on 2023-04-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Название'},
        ),
    ]
